### ISSUE TITLE
Feature request: register as homebrew cask

### ISSUE THREAD

**Issue by Larandar** [spotter-application/spotter#10]
This would make installation easier (`brew install --cask spotter`) and will also handle updates until an update system is available.

**Comment by jet8a** [comment]
<img width="590" alt="image" src="https://user-images.githubusercontent.com/14956407/104836444-58a9aa00-58ae-11eb-99ee-721141ff0f61.png">
Can't do it at the moment

**Comment by jet8a** [comment]
https://github.com/Homebrew/homebrew-cask/pull/98454

**Comment by avioli** [comment]
Got the stars. 27 forks and 25 watchers to go...

**Comment by jet8a** [comment]
Yes, the [pull request](https://github.com/Homebrew/homebrew-cask/pull/98454) has been merged 🎉
