### ISSUE TITLE
Basic Questions: Is this a CLI app or is there a UI component? Crossplatform?

### ISSUE THREAD

**Issue by ndom91** [spotter-application/spotter#11]
Hi Team,

Just had some basic questions for you as this seems interesting, but I'm not sure on a few things yet.

1. Is this a cli application? Or does it open a spotlight / alfred like command palette? A screenshot in the readme would be very helpful!
2. I know MacOS / xcode / etc is mentioned often in the readme, but seeing as its a react native application I wasn't sure if it would also run on Linux. Maybe clarify the platform support in the readme as well?

Anyway thanks for your hard work!

**Comment by jet8a** [comment]
Hi Nico,

1. It's an app with GUI. There are some screenshots in [producthunt](https://www.producthunt.com/posts/spotter-4)
2. At the moment available  only for macOS. Thanks for the comment, I will add it with the next documentation update.
