### ISSUE TITLE
Need investigation: launching spotify via spotter "play" is unresponsive

### ISSUE THREAD

**Issue by Larandar** [spotter-application/spotter#12]
Steps to reproduce:
- Close Spotify
- Query for play or toggle
- Spotify open but does not respond to most mouse events

Might be a Spotify issue, more investigation needed

**Comment by Zaitam** [comment]
> Spotify open but does not respond to most mouse events

Do you see everything black or do you see spotify normal except it doesn't respond?
Can you try this?

- Close Spotify

- Query for play or toggle

- Wait till Spotify opens and press Cmd+Option/Alt+Esc

Now is Spotify icon red? (or has a red text on it's side?)
