### ISSUE TITLE
Issues

### ISSUE THREAD

**Issue by Zaitam** [spotter-application/spotter#3]
I found a list of issues that i will also try to  fix:
1. The app at the start opens in the left corner
2. It cant find apps in the Utilities folder
3. If the items list was long, it somethimes appears upper than ususal when you activate it again
4. (Idk if this is intencional) When you click outside the app it doesn't hide
5.  If the app can't find what you looked for it closes

**Comment by jet8a** [comment]
@Zaitam still relevant?

**Comment by Zaitam** [comment]
yes all except 4
