### ISSUE TITLE
Feature Request: Copy the result of a calculation

### ISSUE THREAD

**Issue by Zaitam** [spotter-application/spotter#4]
If you do a Math calculation, for example : 
![Captura de Pantalla 2020-11-25 a la(s) 13 45 11](https://user-images.githubusercontent.com/71014214/100257216-73057e00-2f24-11eb-8c20-146fdb7dcbdd.png)
And press enter, then you copy the result

**Comment by jet8a** [comment]
Implemented https://github.com/spotter-application/spotter/commit/dfd693aaef5c214125136a918be68da89631cf2e
